media:
  input: static/img
  output: /img

content:
  - name: guia-principal
    label: Guía Principal
    type: collection
    path: docs/guia-principal
    view:
      fields: [title, sidebar_position]
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: sidebar_position
        label: Posición en Sidebar
        type: number
        required: false
      - name: slug
        label: Slug (URL)
        type: string
        required: false
        description: URL personalizada para esta página
      - name: body
        label: Contenido
        type: rich-text

  - name: otras-guias
    label: Otras Guías
    type: collection
    path: docs/otras-guias
    view:
      fields: [title, draft, sidebar_position]
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: sidebar_position
        label: Posición en Sidebar
        type: number
        required: false
      - name: slug
        label: Slug (URL)
        type: string
        required: false
        description: URL personalizada para esta página
      - name: draft
        label: Borrador
        type: boolean
        default: false
        required: false
        description: Marcar como borrador para ocultar la página
      - name: body
        label: Contenido
        type: rich-text

  - name: configuracion
    label: Configuración
    type: collection
    path: docs/configuracion
    view:
      fields: [title, sidebar_position]
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: sidebar_position
        label: Posición en Sidebar
        type: number
        required: false
      - name: slug
        label: Slug (URL)
        type: string
        required: false
        description: URL personalizada para esta página
      - name: body
        label: Contenido
        type: rich-text

  - name: utilidad
    label: Utilidad
    type: collection
    path: docs/utilidad
    view:
      fields: [title, sidebar_position]
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: sidebar_position
        label: Posición en Sidebar
        type: number
        required: false
      - name: slug
        label: Slug (URL)
        type: string
        required: false
        description: URL personalizada para esta página
      - name: body
        label: Contenido
        type: rich-text

  - name: miscelaneo
    label: Misceláneo
    type: collection
    path: docs/miscelaneo
    view:
      fields: [title, sidebar_position]
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: sidebar_position
        label: Posición en Sidebar
        type: number
        required: false
      - name: slug
        label: Slug (URL)
        type: string
        required: false
        description: URL personalizada para esta página
      - name: body
        label: Contenido
        type: rich-text

  - name: intro
    label: Página de Inicio
    type: file
    path: docs/intro.mdx
    fields:
      - name: title
        label: Título
        type: string
        required: true
      - name: slug
        label: Slug (URL)
        type: string
        required: false
      - name: sidebar_position
        label: Posición en Sidebar
        type: number
        required: false
      - name: body
        label: Contenido
        type: rich-text
